/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package market;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A455L
 */
public class dua extends javax.swing.JFrame {

    /**
     * Creates new form dua
     */
    public dua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        b = new javax.swing.JRadioButton();
        alamat = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        pinjam = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        k = new javax.swing.JRadioButton();
        denda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(170, 40, 190, 30);
        getContentPane().add(nama);
        nama.setBounds(170, 80, 190, 30);

        buttonGroup1.add(b);
        b.setText("Belum");
        getContentPane().add(b);
        b.setBounds(280, 160, 53, 23);
        getContentPane().add(alamat);
        alamat.setBounds(170, 120, 190, 30);
        getContentPane().add(jenis);
        jenis.setBounds(170, 200, 190, 30);

        pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamActionPerformed(evt);
            }
        });
        getContentPane().add(pinjam);
        pinjam.setBounds(250, 290, 200, 30);
        getContentPane().add(kembali);
        kembali.setBounds(250, 330, 200, 30);
        getContentPane().add(judul);
        judul.setBounds(170, 240, 190, 30);

        buttonGroup1.add(k);
        k.setText("Kembali");
        getContentPane().add(k);
        k.setBounds(170, 160, 61, 23);
        getContentPane().add(denda);
        denda.setBounds(170, 380, 130, 30);

        jButton1.setText("Lihat Denda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 380, 100, 30);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "NAMA", "ALAMAT", "STATUS", "JENIS", "JUDUL", "TGL PINJAM", "TGL KEMBALI", "DENDA"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 20, 480, 280);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(860, 360, 90, 30);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(860, 320, 90, 20);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 404, 290, 20);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 360, 80, 30);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 320, 70, 20);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 320, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market/kk.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 470);

        setSize(new java.awt.Dimension(1004, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinjamActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
 if("".equals(no.getText()) || "".equals(nama.getText()) || "".equals(alamat.getText()) || "".equals(jenis.getText()) || "".equals(judul.getText()) || "".equals(pinjam.getText()) || "".equals(kembali.getText()) || "".equals(denda.getText())){
            JOptionPane.showMessageDialog(this, "HARAP LENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        } else{
           String s  = "";
           
           if(k.isSelected()){
               s = "Kembali";
           } else{
               s = "Belum";
           }
           String SQL = "INSERT INTO tb_pinjam " + "VALUES('" + no.getText()+ "','"+nama.getText()+"','"+alamat.getText()+"','"+s+"','"+jenis.getText()+"','"+judul.getText()+"','"+pinjam.getText()+"','"+kembali.getText()+"','"+denda.getText()+"')";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "DATA BERHASIL DITAMBAHKAN", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               selectData();
               
           }else{
               JOptionPane.showMessageDialog(this, "DATA GAGAL DITAMBAHKAN", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           }
        }











        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

 MessageFormat header = new MessageFormat("Pengembalian Buku Perpustakaan");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}     ");
        try {
            tbl.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int baris = tbl.getSelectedRow();
       if (baris != -1){
           String No = tbl.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tb_pinjam WHERE no ='"+No+"'";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else{
               JOptionPane.showMessageDialog(this, "DATA GAGAL DIHAPUS", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       }else{
           JOptionPane.showMessageDialog(this, "PILIH BARIS DATA DAHULU", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
           no.setText("");
           nama.setText("");
           alamat.setText("");
           jenis.setText("");
           judul.setText("");
           kembali.setText("");
           pinjam.setText("");
           denda.setText("");
           buttonGroup1.clearSelection();

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        selectData();
                // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       if("".equals(no.getText()) || "".equals(nama.getText()) || "".equals(alamat.getText()) || "".equals(jenis.getText()) || "".equals(judul.getText())|| "".equals(pinjam.getText())|| "".equals(kembali.getText())|| "".equals(denda.getText())){
                JOptionPane.showMessageDialog(this, "HARAP LENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE); 
              } else{
           String s = "";
           
           if(k.isSelected()){
               s = "Kembali";
           } else{
               s = "Belum Kembali";
           }
           String SQL = "UPDATE tb_pinjam SET "
                   + "nama='"+nama.getText()+"', "
                   + "alamat='"+alamat.getText()+"', "
                   + "status='" + s+"', "
                   + "jenis='"+jenis.getText()+"', "
                   + "judul='"+judul.getText()+"', "
                   + "tanggal_pinjam='"+pinjam.getText()+"', "
                   + "tanggal_kembali='"+kembali.getText()+"', "
                   + "denda='"+denda.getText()+"' WHERE no='"+no.getText()+"'";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "DATA BERHASIL DIUPDATE", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               selectData();
               
           }else{
               JOptionPane.showMessageDialog(this, "DATA GAGAL DIUPDATE", "Sukses", JOptionPane.WARNING_MESSAGE);
           }
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
int baris = tbl.getSelectedRow();
        
        if(baris != 1){
            no.setText(tbl.getValueAt(baris, 0).toString());
            nama.setText(tbl.getValueAt(baris, 1).toString());
            if("Kembali".equals(tbl.getValueAt(baris, 3).toString())){
                k.setSelected(true);
            }else{
                b.setSelected(true);
            
            }
            alamat.setText(tbl.getValueAt(baris, 2).toString());
            jenis.setText(tbl.getValueAt(baris, 4).toString());
            judul.setText(tbl.getValueAt(baris, 5).toString());
             pinjam.setText(tbl.getValueAt(baris, 6).toString());
              kembali.setText(tbl.getValueAt(baris, 7).toString());
               denda.setText(tbl.getValueAt(baris, 8).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new denda().setVisible(true);
        this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JRadioButton b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField denda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField judul;
    private javax.swing.JRadioButton k;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JTextField pinjam;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
          String kolom[] = {"no", "nama", "alamat","status","jenis","judul", "tanggal_pinjam", "tanggal_kembali" , "denda"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_pinjam";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String no = rs.getString(1);
               String nama = rs.getString(2);
            
               String alamat = rs.getString(3);
                  String s = "";
               if("Kembali".equals(rs.getString(4))){
                   s = "Kembali";
                   
               }else{
                   s = "Belum Kembali";
                   
               }
               String jenis = rs.getString(5);
               String judul = rs.getString(6);
               String tanggal_pinjam = rs.getString(7);
               String tanggal_kembali = rs.getString(8);
               
                String denda = rs.getString(9);
               String data[] = {no,nama, alamat, s, jenis, judul, tanggal_pinjam, tanggal_kembali, denda};
               dtm.addRow(data);
               
           }
           
       }catch (SQLException ex){
           Logger.getLogger(dua.class.getName()).log(Level.SEVERE, null, ex);
           
       }
       tbl.setModel(dtm);
}}
